export type InsightCategory =
  | "UX Change"
  | "Feature Launch"
  | "Design Trend"
  | "Copy Update"
  | "Flow Change"
  | "Competitive Move";

export interface Insight {
  slug: string;
  date: string;
  title: string;
  summary: string;
  analysis: string;
  impact: "low" | "medium" | "high";
  category: InsightCategory;
  beforeImage?: string;
  afterImage?: string;
  diffPercent?: number;
  flow?: string;
  screenLabel?: string;
}

/**
 * Generated by scripts/generate-insights.mjs
 * Run: ANTHROPIC_API_KEY=... node scripts/generate-insights.mjs
 *
 * This starts empty and is populated after the first diff + insight generation run.
 */
export const insightsBySlug: Record<string, Insight[]> = {};
